### ISSUE TITLE
KeyError: 4 when not connecting probe to target chip

### ISSUE THREAD

**Issue by maxgerhardt** [mraardvark/pyedbglib#6]
As noted [in here](https://community.platformio.org/t/debug-an-avr-4809-with-microupdi/19926/7?u=maxgerhardt), when no chip is connected and the received JTAGICE3 response bytes are garbage, it still tries to unconditionally convert the received byte into an error string according to a map which only has certain entries.

https://github.com/mraardvark/pyedbglib/blob/9739f994a5c479f397fdd8c6c3014055f94b60bd/pyedbglib/protocols/avr8protocol.py#L215-L221

https://github.com/mraardvark/pyedbglib/blob/master/pyedbglib/protocols/avr8protocolerrors.py

https://github.com/mraardvark/pyedbglib/blob/a2f24b0dde1cee6890b38beabba14590b3e97ced/pyedbglib/protocols/avr8protocolerrors.py#L5-L10

![grafik](https://user-images.githubusercontent.com/26485477/111074838-45e5d700-84e5-11eb-841a-d9839c0c0a73.png)

A check would be good here to map this to "unknown error code" or something instead.

**Comment by xoriath** [comment]
Can convert the dict to a collections.defaultdict to default all unknown values...

**Comment by mraardvark** [comment]
Closing - this pyedbglib is EOL.
See https://github.com/microchip-pic-avr-tools/pyedbglib
